[package]
name = "egui-112-keypress-move-circle-with-velocity"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
eframe = "0.24.0" # Gives us egui, epi and web+native backends

